### ISSUE TITLE
Allow protocols other than TCP in service

### ISSUE THREAD

**Issue by iamd3vil** [mr-karan/kubekutr#7]
Currently there is no way to change the protocol in service. It's assumed that it will be `TCP`. There should be an option to configure protocol as well. Default can be `TCP`.

I can a send a PR if this is ok.

**Comment by mr-karan** [comment]
Fix coming soon :tada:

**Comment by mr-karan** [comment]
Pushed https://github.com/mr-karan/kubekutr/releases/tag/0.6.0 which includes this and a bunch of other wholesome features :unicorn: 

Feel free to re-open in case of bugs.
